/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    ACollapse: typeof import('antdv-next')['Collapse']
    AColorPicker: typeof import('antdv-next')['ColorPicker']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADatePicker: typeof import('antdv-next')['DatePicker']
    ADivider: typeof import('antdv-next')['Divider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    AMenu: typeof import('antdv-next')['Menu']
    AModal: typeof import('antdv-next')['Modal']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASelect: typeof import('antdv-next')['Select']
    ASlider: typeof import('antdv-next')['Slider']
    ASwitch: typeof import('antdv-next')['Switch']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    BackupDialog: typeof import('./src/components/BackupDialog.vue')['default']
    CategoryDialog: typeof import('./src/components/CategoryDialog.vue')['default']
    ColorPickerPanel: typeof import('./src/components/ColorPickerPanel.vue')['default']
    NestedTodoList: typeof import('./src/components/NestedTodoList.vue')['default']
    ReminderDialog: typeof import('./src/components/ReminderDialog.vue')['default']
    ReportDialog: typeof import('./src/components/ReportDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    TagDialog: typeof import('./src/components/TagDialog.vue')['default']
    TimeView: typeof import('./src/components/TimeView.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
